### ISSUE TITLE
Highlight failure of hash inside a string

### ISSUE THREAD

**Issue by prozach** [voxpupuli/vim-puppet#6]
For example `"${osfamily}"` works where `"${facts['osfamily']}"` does not.

**Comment by rski** [comment]
This works for me with the new syntax, are you ok with it @zleswomp ?
![newsyntaxpuppet](https://cloud.githubusercontent.com/assets/2960312/20601044/41dc13b6-b25f-11e6-903c-bd770e7c9366.png)

**Comment by prozach** [comment]
@rski I manually added the line change to my checked out version of the repo, but that didn't seem to help at all.  Your example looks good, so maybe there is something special on my system I'm overlooking.

**Comment by rski** [comment]
@zleswomp can you pull the latest commit from master and see if that works?

**Comment by prozach** [comment]
@rski It works!!! I was pulling in the change form #7 manually.  Thank you.

**Comment by prozach** [comment]
Wow, and a bunch of other fixes too.

**Comment by rski** [comment]
yeah it was a big rewrite
